version: '3'
silent: true

# If you are getting permission errors, have a look at this guide ASAP :) 
# https://tinygo.org/docs/guides/tinygo-flash-errors/

tasks:
  default:
    cmds:
      - sudo tinygo flash -target gobadge .

  flash:
    vars:
      CONF: '{{default "tinygo" .CONF}}' # tinygo / fathom / gcuk22 / gcuk23
      NAME: '{{default "TALHA ALTINEL" .NAME}}'
      SLOGAN1: '{{default "Good Things Come" .SLOGAN1}}'
      SLOGAN2: '{{default "In Tiny Packages" .SLOGAN2}}'
    cmds:
      - sudo chmod a+rw /dev/ttyACM0 # https://tinygo.org/docs/guides/tinygo-flash-errors/
      - go run cmd/main.go -conf={{.CONF}}
      - tinygo flash -size short -target gobadge -ldflags="-X main.Name='{{.NAME}}' -X main.Slogan1='{{.SLOGAN1}}' -X main.Slogan2='{{.SLOGAN2}}'" .

  flash-gophercon:
    cmds:
      - task: flash 
        vars:
          CONF: gcuk23
          